name: flutter_module
description: A new flutter module project.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #网络请求
  dio: ^1.0.9
  #网络检查
  connectivity: ^0.3.2
  event_bus:  ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  module:
    androidPackage: com.example.fluttermodule
    iosBundleIdentifier: com.example.flutterModule

  fonts:
    - family: myIconFont
      fonts:
        - asset: assets/font/iconfont.ttf
